
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("w", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("u", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.16666666666666785, bpm)
keypress("g", x, bpm)
rest(0.1666666666666643, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.6666666666666572, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.6666666666666856, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.6666666666666572, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.14375000000001137, bpm)
keypress("0", x, bpm)
rest(0.14374999999998295, bpm)
keypress("q", x, bpm)
rest(0.14375000000001137, bpm)
keypress("e", x, bpm)
rest(0.14374999999998295, bpm)
keypress("y", x, bpm)
rest(0.14375000000001137, bpm)
keypress("u", x, bpm)
rest(0.14375000000001137, bpm)
keypress("i", x, bpm)
rest(0.13749999999998863, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.14375000000001137, bpm)
keypress("d", x, bpm)
rest(0.14374999999998295, bpm)
keypress("u", x, bpm)
rest(0.14375000000001137, bpm)
keypress("i", x, bpm)
rest(0.14374999999998295, bpm)
keypress("p", x, bpm)
rest(0.14375000000001137, bpm)
keypress("d", x, bpm)
rest(0.14375000000001137, bpm)
keypress("f", x, bpm)
rest(0.13749999999998863, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.14375000000001137, bpm)
keypress("h", x, bpm)
rest(0.14374999999998295, bpm)
keypress("j", x, bpm)
rest(0.14375000000001137, bpm)
keypress("z", x, bpm)
rest(0.14374999999998295, bpm)
keypress("x", x, bpm)
rest(0.14375000000001137, bpm)
keypress("c", x, bpm)
rest(0.14375000000001137, bpm)
keypress("b", x, bpm)
rest(0.13749999999998863, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("A#0", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("c", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(0.08333333333331439, bpm)
keypress("E", x, bpm)
rest(0.08333333333337123, bpm)
keypress("e", x, bpm)
rest(0.08333333333331439, bpm)
keypress("y", x, bpm)
rest(0.08333333333331439, bpm)
keypress("I", x, bpm)
rest(0.08333333333337123, bpm)
keypress("p", x, bpm)
rest(0.08333333333331439, bpm)
keypress("I", x, bpm)
rest(0.08333333333331439, bpm)
keypress("P", x, bpm)
rest(0.08333333333337123, bpm)
keypress("p", x, bpm)
rest(0.08333333333331439, bpm)
keypress("d", x, bpm)
rest(0.08333333333331439, bpm)
keypress("G", x, bpm)
rest(0.08333333333337123, bpm)
keypress("j", x, bpm)
rest(0.08333333333331439, bpm)
keypress("G", x, bpm)
rest(0.08333333333331439, bpm)
keypress("J", x, bpm)
rest(0.08333333333337123, bpm)
keypress("j", x, bpm)
rest(0.08333333333331439, bpm)
keypress("z", x, bpm)
rest(0.08333333333331439, bpm)
keypress("C", x, bpm)
rest(0.08333333333337123, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("B", x, bpm)
rest(0.08333333333331439, bpm)
keypress("b", x, bpm)
rest(0.08333333333337123, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("B", x, bpm)
rest(0.08333333333337123, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("J", x, bpm)
rest(0.08333333333337123, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("j", x, bpm)
rest(0.08333333333331439, bpm)
keypress("J", x, bpm)
rest(0.08333333333337123, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
rest(0.08333333333331439, bpm)
keypress("j", x, bpm)
rest(0.08333333333331439, bpm)
keypress("P", x, bpm)
rest(0.08333333333337123, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.08333333333331439, bpm)
keypress("p", x, bpm)
rest(0.08333333333331439, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.08333333333337123, bpm)
keypress("p", x, bpm)
rest(0.08333333333331439, bpm)
keypress("E", x, bpm)
rest(0.08333333333331439, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.08333333333337123, bpm)
keypress("e", x, bpm)
rest(0.08333333333331439, bpm)
keypress("E", x, bpm)
rest(0.08333333333331439, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.08333333333337123, bpm)
keypress("e", x, bpm)
rest(0.08333333333331439, bpm)
keypress("^", x, bpm)
rest(0.08333333333331439, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.08333333333337123, bpm)
keypress("6", x, bpm)
rest(0.08333333333331439, bpm)
keypress("^", x, bpm)
rest(0.08333333333331439, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.08333333333337123, bpm)
keypress("6", x, bpm)
rest(0.08333333333331439, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.13125000000002274, bpm)
keypress("p", x, bpm)
rest(0.13333333333332575, bpm)
keypress("d", x, bpm)
rest(0.13541666666662877, bpm)
keypress("G", x, bpm)
rest(0.6000000000000227, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)


finishedSong()
