
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(2.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
rest(0.04374999999998863, bpm)
keypress("I", x, bpm)
rest(0.04374999999998863, bpm)
keypress("p", x, bpm)
rest(0.043750000000045475, bpm)
keypress("d", x, bpm)


finishedSong()
