
keypress("i", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(4, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(2.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(4, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("9", x, bpm)
rest(4, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("^", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(3, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
keypress("d", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(3, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(4, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("g", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(2.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("^", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("2", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("O", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(2.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("d", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(3, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(4, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(4, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(4, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(2.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(4, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("d", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("P", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(4, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(4, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(4, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("d", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(4, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(4, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(4, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(3.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)


finishedSong()
