

keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)


finishedSong()
