
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.0833333333333357, bpm)
keypress("o", x, bpm)
rest(0.1666666666666643, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.1666666666666714, bpm)
keypress("S", x, bpm)
rest(0.1666666666666572, bpm)
keypress("D", x, bpm)
rest(0.1666666666666714, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.1666666666666714, bpm)
keypress("G", x, bpm)
rest(0.1666666666666572, bpm)
keypress("h", x, bpm)
rest(0.1666666666666714, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.1666666666666572, bpm)
keypress("O", x, bpm)
rest(0.16666666666668561, bpm)
keypress("s", x, bpm)
rest(0.1666666666666572, bpm)
keypress("S", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.1666666666666572, bpm)
keypress("D", x, bpm)
rest(0.16666666666668561, bpm)
keypress("g", x, bpm)
rest(0.1666666666666572, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("D", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("D", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("!", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("5", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("!", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)


finishedSong()
