


-- 1

keypress("QS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("IS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Qd", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("IS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("eS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("ed", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("*S", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*d", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9S", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Ia", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9S", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Id", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("QS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Qd", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("eS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("ed", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("*S", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*d", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9S", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Ia", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Qa", x, bpm)
rest(1, 92)
keypress("QTS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("eTS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("*TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("9TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("Ta", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("Td", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!QTS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("2TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("e!TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("2TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("2TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rT", x, bpm)
rest(0.25, bpm)
keypress("eO", x, bpm)
rest(0.25, bpm)
keypress("y!TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!Ta", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("2TS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("ep", x, bpm)
rest(0.25, bpm)
keypress("!Td", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ry", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!$*Tep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("T2p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!T60ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("T2p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!*WT0p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("T2p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!QT9ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("T2p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("!Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("$*Tep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("T60ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*WT0p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("QT9ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rS", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("$*Tep", x, bpm)
rest(0.5, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("T69ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("*WT0p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("QT9ep", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("$*Tep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("T60ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("*WT0p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("QT9ep", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("rO", x, bpm)
rest(0.25, bpm)
keypress("eI", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("*TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("Wra", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("*TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("Wra", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("*TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("Wra", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("*TS", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("Wra", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("9TS", x, bpm)
rest(0.25, bpm)
keypress("Qy", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("Qep", x, bpm)
rest(0.25, bpm)
keypress("9TS", x, bpm)
rest(0.25, bpm)
keypress("Qy", x, bpm)
rest(0.25, bpm)
keypress("era", x, bpm)
rest(0.25, bpm)
keypress("Qep", x, bpm)
rest(0.25, bpm)
keypress("9TS", x, bpm)
rest(0.25, bpm)
keypress("$Q2y", x, bpm)
rest(0.25, bpm)
keypress("13era", x, bpm)
rest(0.25, bpm)
keypress("^Q2ep", x, bpm)
rest(0.25, bpm)
keypress("69!TS", x, bpm)
rest(0.25, bpm)
keypress("Q57y", x, bpm)
rest(0.25, bpm)
keypress("46era", x, bpm)
rest(0.25, bpm)
keypress("%Q3ep", x, bpm)
rest(0.25, bpm)
keypress("$T2p", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("e*I", x, bpm)
rest(0.25, bpm)
keypress("$Tp", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("e*I", x, bpm)
rest(0.25, bpm)
keypress("$Tp", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("e*I", x, bpm)
rest(0.25, bpm)
keypress("$Tp", x, bpm)
rest(0.25, bpm)
keypress("*T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("e*I", x, bpm)
rest(0.25, bpm)
keypress("T6p", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("T6p", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("T6p", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("T6p", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("*Tp", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("rWO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("*Tp", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("rWO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("*Tp", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("rWO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("*Tp", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("rWO", x, bpm)
rest(0.25, bpm)
keypress("0eI", x, bpm)
rest(0.25, bpm)
keypress("T9p", x, bpm)
rest(0.25, bpm)
keypress("QT", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("eQI", x, bpm)
rest(0.25, bpm)
keypress("T9p", x, bpm)
rest(0.25, bpm)
keypress("QT", x, bpm)
rest(0.25, bpm)
keypress("erO", x, bpm)
rest(0.25, bpm)
keypress("eQI", x, bpm)
rest(0.25, bpm)
keypress("T9p", x, bpm)
rest(0.25, bpm)
keypress("QT", x, bpm)
rest(0.25, bpm)
keypress("0rO", x, bpm)
rest(0.25, bpm)
keypress("9eI", x, bpm)
rest(0.25, bpm)
keypress("*Tp", x, bpm)
rest(0.25, bpm)
keypress("7T", x, bpm)
rest(0.25, bpm)
keypress("6rO", x, bpm)
rest(0.25, bpm)
keypress("e%I", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$Td", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("T6d", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("!Td", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("2TS", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("Qry", x, bpm)
rest(0.25, bpm)
keypress("6eI", x, bpm)
rest(0.25, bpm)
keypress("2aTS", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("Qry", x, bpm)
rest(0.25, bpm)
keypress("6eI", x, bpm)
rest(0.25, bpm)
keypress("TS2", x, bpm)
rest(0.25, bpm)
keypress("QI", x, bpm)
rest(0.25, bpm)
keypress("0ry", x, bpm)
rest(0.25, bpm)
keypress("9eI", x, bpm)
rest(0.25, bpm)
keypress("*Td", x, bpm)
rest(0.25, bpm)
keypress("7I", x, bpm)
rest(0.25, bpm)
keypress("6ry", x, bpm)
rest(0.25, bpm)
keypress("e%I", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$Td", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("$TS", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("*ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("T6d", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("6TS", x, bpm)
rest(0.25, bpm)
keypress("0p", x, bpm)
rest(0.25, bpm)
keypress("erT", x, bpm)
rest(0.25, bpm)
keypress("0ep", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("!S", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("!Td", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("!TS", x, bpm)
rest(0.25, bpm)
keypress("%O", x, bpm)
rest(0.25, bpm)
keypress("0rT", x, bpm)
rest(0.25, bpm)
keypress("e%O", x, bpm)
rest(0.25, bpm)
keypress("2TS", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("Qry", x, bpm)
rest(0.25, bpm)
keypress("6eI", x, bpm)
rest(0.25, bpm)
keypress("2aTS", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("Qry", x, bpm)
rest(0.25, bpm)
keypress("6eI", x, bpm)
rest(0.25, bpm)
keypress("TS2", x, bpm)
rest(0.25, bpm)
keypress("QI", x, bpm)
rest(0.25, bpm)
keypress("0ry", x, bpm)
rest(0.25, bpm)
keypress("9eI", x, bpm)
rest(0.25, bpm)
keypress("*Td", x, bpm)
rest(0.25, bpm)
keypress("7I", x, bpm)
rest(0.25, bpm)
keypress("6ry", x, bpm)
rest(0.25, bpm)
keypress("e%I", x, bpm)
rest(0.25, bpm)
keypress("$TL", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("*ej", x, bpm)
rest(0.25, bpm)
keypress("$TL", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("*ej", x, bpm)
rest(0.25, bpm)
keypress("$Tz", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("*ej", x, bpm)
rest(0.25, bpm)
keypress("$TL", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("*ej", x, bpm)
rest(0.25, bpm)
keypress("6TL", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("0ej", x, bpm)
rest(0.25, bpm)
keypress("6TL", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("0ej", x, bpm)
rest(0.25, bpm)
keypress("T6z", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("0ej", x, bpm)
rest(0.25, bpm)
keypress("6TL", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("erS", x, bpm)
rest(0.25, bpm)
keypress("0ej", x, bpm)
rest(0.25, bpm)
keypress("!TL", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0rS", x, bpm)
rest(0.25, bpm)
keypress("e%H", x, bpm)
rest(0.25, bpm)
keypress("!TL", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0rS", x, bpm)
rest(0.25, bpm)
keypress("e%H", x, bpm)
rest(0.25, bpm)
keypress("!Tz", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0rS", x, bpm)
rest(0.25, bpm)
keypress("e%H", x, bpm)
rest(0.25, bpm)
keypress("!TL", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0rS", x, bpm)
rest(0.25, bpm)
keypress("e%H", x, bpm)
rest(0.25, bpm)
keypress("2TL", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qrd", x, bpm)
rest(0.25, bpm)
keypress("6eG", x, bpm)
rest(0.25, bpm)
keypress("T2k", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qrd", x, bpm)
rest(0.25, bpm)
keypress("6eG", x, bpm)
rest(0.25, bpm)
keypress("2TL", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("0rd", x, bpm)
rest(0.25, bpm)
keypress("9eG", x, bpm)
rest(0.25, bpm)
keypress("*Tz", x, bpm)
rest(0.25, bpm)
keypress("7G", x, bpm)
rest(0.25, bpm)
keypress("6rd", x, bpm)
rest(0.25, bpm)
keypress("e%G", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$z", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6z", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!z", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qd", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2k", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qd", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("0d", x, bpm)
rest(0.25, bpm)
keypress("9G", x, bpm)
rest(0.25, bpm)
keypress("*z", x, bpm)
rest(0.25, bpm)
keypress("7G", x, bpm)
rest(0.25, bpm)
keypress("6d", x, bpm)
rest(0.25, bpm)
keypress("%G", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("!*p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("29p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("$*Qp", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("60ep", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("!%*p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("269p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("269p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("$*Qp", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("60ep", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("!%*p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("269p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("2p", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("9T", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("2p", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("9T", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("2p", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("9T", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("2p", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("9T", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("$p", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("*I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("6p", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("eT", x, bpm)
rest(0.25, bpm)
keypress("0I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("!O", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("2p", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("QT", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("2p", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("QT", x, bpm)
rest(0.25, bpm)
keypress("6I", x, bpm)
rest(0.25, bpm)
keypress("9p", x, bpm)
rest(0.25, bpm)
keypress("QI", x, bpm)
rest(0.25, bpm)
keypress("0T", x, bpm)
rest(0.25, bpm)
keypress("9I", x, bpm)
rest(0.25, bpm)
keypress("*p", x, bpm)
rest(0.25, bpm)
keypress("7I", x, bpm)
rest(0.25, bpm)
keypress("6T", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("$S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ed", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6eS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("ed", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*WS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Wd", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("9QS", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("QI", x, bpm)
rest(0.25, bpm)
keypress("0y", x, bpm)
rest(0.25, bpm)
keypress("9I", x, bpm)
rest(0.25, bpm)
keypress("*d", x, bpm)
rest(0.25, bpm)
keypress("7I", x, bpm)
rest(0.25, bpm)
keypress("6y", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("$S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("60S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*WS", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Wd", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("9QS", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("QI", x, bpm)
rest(0.25, bpm)
keypress("0y", x, bpm)
rest(0.25, bpm)
keypress("9I", x, bpm)
rest(0.25, bpm)
keypress("*d", x, bpm)
rest(0.25, bpm)
keypress("7I", x, bpm)
rest(0.25, bpm)
keypress("6y", x, bpm)
rest(0.25, bpm)
keypress("%I", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$z", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6z", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!z", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qd", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2k", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qd", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("0d", x, bpm)
rest(0.25, bpm)
keypress("9G", x, bpm)
rest(0.25, bpm)
keypress("*z", x, bpm)
rest(0.25, bpm)
keypress("7G", x, bpm)
rest(0.25, bpm)
keypress("6d", x, bpm)
rest(0.25, bpm)
keypress("%G", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$z", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6z", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!z", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qd", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2k", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qd", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("0d", x, bpm)
rest(0.25, bpm)
keypress("9G", x, bpm)
rest(0.25, bpm)
keypress("*z", x, bpm)
rest(0.25, bpm)
keypress("7G", x, bpm)
rest(0.25, bpm)
keypress("6d", x, bpm)
rest(0.25, bpm)
keypress("%G", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$z", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6z", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!z", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("QS", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2k", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("QS", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("9G", x, bpm)
rest(0.25, bpm)
keypress("*z", x, bpm)
rest(0.25, bpm)
keypress("7G", x, bpm)
rest(0.25, bpm)
keypress("6S", x, bpm)
rest(0.25, bpm)
keypress("%G", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$z", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("$L", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("*j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6z", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("6L", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.25, bpm)
keypress("0j", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!z", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("!L", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("0S", x, bpm)
rest(0.25, bpm)
keypress("%H", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("QS", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2k", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("QS", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("2L", x, bpm)
rest(0.25, bpm)
keypress("6G", x, bpm)
rest(0.25, bpm)
keypress("Qf", x, bpm)
rest(0.25, bpm)
keypress("6d", x, bpm)
rest(0.25, bpm)
keypress("2S", x, bpm)
rest(0.25, bpm)
keypress("6a", x, bpm)
rest(0.25, bpm)
keypress("Qp", x, bpm)
rest(0.25, bpm)
keypress("6O", x, bpm)
rest(1, 92)
rest(1, 92)
rest(1, 92)
rest(1, 92)
keypress("QS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("IS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Qd", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("IS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("eS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("ed", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("*S", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*d", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9S", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Ia", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Ia", x, bpm)
rest(1, 92)
keypress("QS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("IS", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Qd", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("IS", x, bpm)
rest(0.5, bpm)
keypress("Tp", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("eS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("ed", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("pS", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("*S", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*d", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("uS", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9S", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Ia", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9S", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Id", x, bpm)
rest(0.25, bpm)

finishedSong()
