
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.3333333333333286, bpm)
keypress("o", x, bpm)
rest(0.1666666666666714, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333286, bpm)
keypress("o", x, bpm)
rest(0.1666666666666714, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.3333333333333286, bpm)
keypress("h", x, bpm)
rest(0.1666666666666714, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333286, bpm)
keypress("h", x, bpm)
rest(0.1666666666666714, bpm)
keypress("G", x, bpm)
rest(0.3333333333333286, bpm)
keypress("G", x, bpm)
rest(0.1666666666666714, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333286, bpm)
keypress("p", x, bpm)
rest(0.1666666666666714, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333286, bpm)
keypress("I", x, bpm)
rest(0.1666666666666714, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.3333333333333428, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.3333333333333428, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("G", x, bpm)
rest(0.3333333333333428, bpm)
keypress("G", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("f", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("p", x, bpm)
rest(0.1666666666666572, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("I", x, bpm)
rest(0.1666666666666572, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("k", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("k", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666572, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666572, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666572, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666572, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.08333333333334281, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666572, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.08333333333334281, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.1666666666666572, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.1666666666666572, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.1666666666666572, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.3333333333333144, bpm)
keypress("o", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333144, bpm)
keypress("o", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.3333333333333144, bpm)
keypress("h", x, bpm)
rest(0.16666666666668561, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333144, bpm)
keypress("h", x, bpm)
rest(0.16666666666668561, bpm)
keypress("G", x, bpm)
rest(0.3333333333333144, bpm)
keypress("G", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333144, bpm)
keypress("p", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333144, bpm)
keypress("I", x, bpm)
rest(0.16666666666668561, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.3333333333333144, bpm)
keypress("o", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333144, bpm)
keypress("o", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.3333333333333144, bpm)
keypress("h", x, bpm)
rest(0.16666666666668561, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.3333333333333144, bpm)
keypress("h", x, bpm)
rest(0.16666666666668561, bpm)
keypress("G", x, bpm)
rest(0.3333333333333144, bpm)
keypress("G", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333144, bpm)
keypress("p", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.3333333333333144, bpm)
keypress("I", x, bpm)
rest(0.16666666666668561, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)


finishedSong()
