
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.11458333333334281, bpm)
keypress("f", x, bpm)
rest(0.11666666666664582, bpm)
keypress("L", x, bpm)
rest(0.26875000000001137, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.11458333333334281, bpm)
keypress("o", x, bpm)
rest(0.11458333333331439, bpm)
keypress("a", x, bpm)
rest(0.2708333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("f", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.11458333333334281, bpm)
keypress("f", x, bpm)
rest(0.11666666666664582, bpm)
keypress("L", x, bpm)
rest(0.26875000000001137, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.11458333333334281, bpm)
keypress("o", x, bpm)
rest(0.11458333333331439, bpm)
keypress("a", x, bpm)
rest(0.2708333333333428, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("f", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)


finishedSong()
