
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("c", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(0.20208333333332007, bpm)
keypress("z", x, bpm)
rest(1.79791666666668, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)


finishedSong()
