

keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.09583333333333321, bpm)
keypress("e", x, bpm)
rest(0.10000000000000009, bpm)
keypress("t", x, bpm)
rest(1.3041666666666667, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.09791666666666643, bpm)
keypress("q", x, bpm)
rest(0.09999999999999964, bpm)
keypress("e", x, bpm)
rest(1.302083333333334, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.09791666666666643, bpm)
keypress("q", x, bpm)
rest(0.09999999999999964, bpm)
keypress("e", x, bpm)
rest(0.8020833333333339, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.09791666666666643, bpm)
keypress("9", x, bpm)
rest(0.09999999999999964, bpm)
keypress("q", x, bpm)
rest(1.802083333333334, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.09791666666666643, bpm)
keypress("8", x, bpm)
rest(0.10000000000000142, bpm)
keypress("q", x, bpm)
rest(0.30208333333333215, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.09583333333333144, bpm)
keypress("0", x, bpm)
rest(0.09999999999999432, bpm)
keypress("w", x, bpm)


finishedSong()
