

keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("b", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)


finishedSong()
