

keypress("v", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("x", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("m", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.33333333333333215, bpm)
keypress("a", x, bpm)
rest(0.16666666666666785, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.33333333333333215, bpm)
keypress("d", x, bpm)
rest(0.16666666666666785, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.33333333333333215, bpm)
keypress("a", x, bpm)
rest(0.16666666666666785, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.33333333333333215, bpm)
keypress("f", x, bpm)
rest(0.16666666666666785, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.33333333333333215, bpm)
keypress("d", x, bpm)
rest(0.16666666666666785, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.33333333333333215, bpm)
keypress("u", x, bpm)
rest(0.16666666666666785, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333357, bpm)
keypress("a", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333357, bpm)
keypress("d", x, bpm)
rest(0.1666666666666643, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333357, bpm)
keypress("a", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333357, bpm)
keypress("d", x, bpm)
rest(0.1666666666666643, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333357, bpm)
keypress("a", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333357, bpm)
keypress("d", x, bpm)
rest(0.1666666666666643, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333357, bpm)
keypress("a", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333357, bpm)
keypress("f", x, bpm)
rest(0.1666666666666643, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333357, bpm)
keypress("d", x, bpm)
rest(0.1666666666666643, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333357, bpm)
keypress("u", x, bpm)
rest(0.1666666666666643, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("d", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("d", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("d", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("d", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.3333333333333286, bpm)
keypress("a", x, bpm)
rest(0.1666666666666714, bpm)
keypress("s", x, bpm)
rest(0.3333333333333286, bpm)
keypress("f", x, bpm)
rest(0.1666666666666714, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("m", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("m", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("m", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("m", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("m", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("m", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.375, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333428, bpm)
keypress("x", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333428, bpm)
keypress("j", x, bpm)
rest(0.1666666666666572, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333428, bpm)
keypress("j", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333428, bpm)
keypress("x", x, bpm)
rest(0.1666666666666572, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("g", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333428, bpm)
keypress("g", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333428, bpm)
keypress("v", x, bpm)
rest(0.1666666666666572, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("v", x, bpm)
rest(0.1666666666666572, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.3333333333333428, bpm)
keypress("z", x, bpm)
rest(0.1666666666666572, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333428, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.3333333333333428, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333428, bpm)
keypress("z", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333428, bpm)
keypress("x", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333428, bpm)
keypress("j", x, bpm)
rest(0.1666666666666572, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333428, bpm)
keypress("j", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333428, bpm)
keypress("x", x, bpm)
rest(0.1666666666666572, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("g", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333428, bpm)
keypress("g", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333428, bpm)
keypress("v", x, bpm)
rest(0.1666666666666572, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333428, bpm)
keypress("l", x, bpm)
rest(0.1666666666666572, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("v", x, bpm)
rest(0.1666666666666572, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.3333333333333428, bpm)
keypress("z", x, bpm)
rest(0.1666666666666572, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333428, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("z", x, bpm)
keypress("5", x, bpm)
rest(0.3333333333333428, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333428, bpm)
keypress("z", x, bpm)
rest(0.1666666666666572, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.3333333333333428, bpm)
keypress("a", x, bpm)
rest(0.1666666666666572, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.3333333333333428, bpm)
keypress("f", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
rest(0.3333333333333428, bpm)
keypress("f", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.3333333333333428, bpm)
keypress("d", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.3333333333333428, bpm)
keypress("a", x, bpm)
rest(0.1666666666666572, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.3333333333333428, bpm)
keypress("f", x, bpm)
rest(0.1666666666666572, bpm)
keypress("d", x, bpm)
rest(0.3333333333333428, bpm)
keypress("f", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.3333333333333144, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333144, bpm)
keypress("a", x, bpm)
rest(0.16666666666668561, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333144, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.3333333333333144, bpm)
keypress("a", x, bpm)
rest(0.16666666666668561, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.3333333333333144, bpm)
keypress("f", x, bpm)
rest(0.16666666666668561, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333144, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333144, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333144, bpm)
keypress("u", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333144, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333144, bpm)
keypress("d", x, bpm)
rest(0.16666666666668561, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.3333333333333144, bpm)
keypress("u", x, bpm)
rest(0.16666666666668561, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.75, bpm)
keypress("x", x, bpm)


finishedSong()
