
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.03125, bpm)
keypress("D", x, bpm)
rest(0.03125, bpm)
keypress("g", x, bpm)
rest(0.03125, bpm)
keypress("G", x, bpm)
rest(0.03125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("I", x, bpm)
rest(0.09583333333333144, bpm)
keypress("o", x, bpm)
rest(0.02916666666666856, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("I", x, bpm)
rest(0.09583333333333144, bpm)
keypress("o", x, bpm)
rest(0.02916666666666856, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.01458333333333428, bpm)
keypress("Y", x, bpm)
rest(0.01666666666666572, bpm)
keypress("i", x, bpm)
rest(0.01458333333333428, bpm)
keypress("I", x, bpm)
rest(0.01666666666666572, bpm)
keypress("o", x, bpm)
rest(0.0625, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.03125, bpm)
keypress("D", x, bpm)
rest(0.03125, bpm)
keypress("g", x, bpm)
rest(0.03125, bpm)
keypress("G", x, bpm)
rest(0.03125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.03125, bpm)
keypress("D", x, bpm)
rest(0.03125, bpm)
keypress("g", x, bpm)
rest(0.03125, bpm)
keypress("G", x, bpm)
rest(0.03125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.4375, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.375, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.3125, bpm)
keypress("s", x, bpm)
rest(0.1875, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("Z", x, bpm)
rest(0.125, bpm)
keypress("c", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("B", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("m", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("m", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333286, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666714, bpm)
keypress("t", x, bpm)
rest(0.1666666666666714, bpm)
keypress("i", x, bpm)
rest(0.3333333333333286, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.3333333333333286, bpm)
keypress("i", x, bpm)
rest(0.1666666666666714, bpm)
keypress("E", x, bpm)
rest(0.1666666666666714, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333286, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333286, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666714, bpm)
keypress("t", x, bpm)
rest(0.1666666666666714, bpm)
keypress("i", x, bpm)
rest(0.3333333333333286, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.3333333333333286, bpm)
keypress("i", x, bpm)
rest(0.1666666666666714, bpm)
keypress("E", x, bpm)
rest(0.1666666666666714, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333286, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.3333333333333286, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666714, bpm)
keypress("W", x, bpm)
rest(0.1666666666666714, bpm)
keypress("t", x, bpm)
rest(0.3333333333333286, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333286, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666714, bpm)
keypress("t", x, bpm)
rest(0.1666666666666714, bpm)
keypress("i", x, bpm)
rest(0.3333333333333286, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.3333333333333286, bpm)
keypress("i", x, bpm)
rest(0.1666666666666714, bpm)
keypress("E", x, bpm)
rest(0.1666666666666714, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333286, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.09583333333333144, bpm)
keypress("s", x, bpm)
rest(0.15416666666666856, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.3333333333333286, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666714, bpm)
keypress("t", x, bpm)
rest(0.1666666666666714, bpm)
keypress("i", x, bpm)
rest(0.3333333333333286, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
rest(0.3333333333333286, bpm)
keypress("i", x, bpm)
rest(0.1666666666666714, bpm)
keypress("E", x, bpm)
rest(0.1666666666666714, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333286, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
rest(0.3333333333333286, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666714, bpm)
keypress("W", x, bpm)
rest(0.1666666666666714, bpm)
keypress("t", x, bpm)
rest(0.3333333333333286, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.03125, bpm)
keypress("(", x, bpm)
rest(0.03125, bpm)
keypress("q", x, bpm)
rest(0.03125, bpm)
keypress("Q", x, bpm)
rest(0.03125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("^", x, bpm)
rest(0.03125, bpm)
keypress("(", x, bpm)
rest(0.03125, bpm)
keypress("q", x, bpm)
rest(0.03125, bpm)
keypress("Q", x, bpm)
rest(0.03125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("^", x, bpm)
rest(0.03125, bpm)
keypress("(", x, bpm)
rest(0.03125, bpm)
keypress("q", x, bpm)
rest(0.03125, bpm)
keypress("Q", x, bpm)
rest(0.03125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("^", x, bpm)
rest(0.03125, bpm)
keypress("(", x, bpm)
rest(0.03125, bpm)
keypress("q", x, bpm)
rest(0.03125, bpm)
keypress("Q", x, bpm)
rest(0.03125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("7", x, bpm)
rest(0.375, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.875, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.03125, bpm)
keypress("Y", x, bpm)
rest(0.03125, bpm)
keypress("i", x, bpm)
rest(0.03125, bpm)
keypress("I", x, bpm)
rest(0.03125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.09583333333333144, bpm)
keypress("s", x, bpm)
rest(0.15416666666666856, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.3333333333333428, bpm)
keypress("o", x, bpm)
rest(0.1666666666666572, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.1666666666666572, bpm)
keypress("I", x, bpm)
rest(0.3333333333333428, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666572, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.1666666666666572, bpm)
keypress("t", x, bpm)
rest(0.3333333333333428, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.375, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.375, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1.125, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)


finishedSong()
