
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)


finishedSong()
