

keypress("g", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.13124999999999964, bpm)
keypress("T", x, bpm)
rest(0.13125000000000053, bpm)
keypress("i", x, bpm)
rest(0.7374999999999998, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(1.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.13124999999999964, bpm)
keypress("E", x, bpm)
rest(0.13124999999999964, bpm)
keypress("T", x, bpm)
rest(0.2375000000000007, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.13125000000000142, bpm)
keypress("Q", x, bpm)
rest(0.13124999999999787, bpm)
keypress("r", x, bpm)
rest(0.7375000000000007, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(1.5, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.13125000000000142, bpm)
keypress("W", x, bpm)
rest(0.13124999999999787, bpm)
keypress("i", x, bpm)
rest(0.2375000000000007, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(2.5, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(2.5, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(2.5, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(2.5, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(4, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.025000000000005684, bpm)
keypress("S", x, bpm)
rest(0.027083333333322912, bpm)
keypress("g", x, bpm)


finishedSong()
