

keypress("q", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("g", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("d", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("7", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(1, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("^", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("E", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("q", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("p", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("j", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("P", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("d", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("f", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("g", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("d", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("7", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(1, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("^", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("E", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("q", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("p", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("j", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("P", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("d", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("f", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("x", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("k", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("n", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.375, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.375, bpm * 2)
keypress("c", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("z", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("J", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("^", x, bpm * 2)
keypress("B", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("E", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("B", x, bpm * 2)
keypress("5", x, bpm * 2)
keypress("B", x, bpm * 2)
keypress("w", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("B", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("B", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("b", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
keypress("5", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("w", x, bpm * 2)
rest(1, bpm * 2)
keypress("j", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("j", x, bpm * 2)
keypress("4", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("q", x, bpm * 2)
rest(1, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("g", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("j", x, bpm * 2)
keypress("4", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("q", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("2", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("9", x, bpm * 2)
rest(1, bpm * 2)
keypress("G", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("C", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("d", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("a", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("k", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("L", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("L", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("Z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("C", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("V", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("B", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("B", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("B", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("V", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("V", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("C", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("Z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("L", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("a", x, bpm * 2)
keypress("k", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("v", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(1, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(1, bpm * 2)
keypress("a", x, bpm * 2)
keypress("k", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("f", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(3, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(2, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("v", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
keypress("5", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("w", x, bpm * 2)
rest(1, bpm * 2)
keypress("v", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("v", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("c", x, bpm * 2)
rest(1, bpm * 2)
keypress("z", x, bpm * 2)
keypress("7", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("r", x, bpm * 2)
rest(1, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(2, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(2, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("^", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("E", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("p", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("J", x, bpm * 2)
keypress("B", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("l", x, bpm * 2)
rest(1.25, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("x", x, bpm * 2)
rest(1, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("x", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("9", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("8", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(2, bpm * 2)
keypress("i", x, bpm * 2)
keypress("g", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("u", x, bpm * 2)
keypress("f", x, bpm * 2)
rest(3.5, bpm * 2)
keypress("i", x, bpm * 2)
keypress("g", x, bpm * 2)
rest(4.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("(", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("Y", x, bpm * 2)
rest(2.5, bpm * 2)
keypress("a", x, bpm * 2)
keypress("k", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("v", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("j", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1, bpm * 2)
keypress("h", x, bpm * 2)
keypress("v", x, bpm * 2)
rest(1, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.75, bpm * 2)
keypress("s", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(0.25, bpm * 2)
keypress("d", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(3, bpm * 2)
keypress("w", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("g", x, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("9", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("h", x, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("P", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("^", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
keypress("E", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1, bpm * 2)
keypress("p", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(1, bpm * 2)
keypress("P", x, bpm * 2)
keypress("J", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(1, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("0", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("u", x, bpm * 2)
rest(1, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(1, bpm * 2)
keypress("d", x, bpm * 2)
keypress("z", x, bpm * 2)
rest(1, bpm * 2)
keypress("f", x, bpm * 2)
keypress("x", x, bpm * 2)
rest(3, bpm * 2)
keypress("g", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(3, bpm * 2)
keypress("f", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(3, bpm * 2)
keypress("g", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(3, bpm * 2)
keypress("f", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
keypress("g", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(3, bpm * 2)
keypress("f", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
keypress("g", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("c", x, bpm * 2)
keypress("j", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("Y", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("j", x, bpm * 2)
keypress("D", x, bpm * 2)
rest(2.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("h", x, bpm * 2)
keypress("d", x, bpm * 2)
keypress("a", x, bpm * 2)
rest(1, bpm * 2)
keypress("v", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("y", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("b", x, bpm * 2)
keypress("h", x, bpm * 2)
keypress("d", x, bpm * 2)
keypress("p", x, bpm * 2)
rest(1, bpm * 2)
keypress("v", x, bpm * 2)
rest(1, bpm * 2)
keypress("c", x, bpm * 2)
rest(1, bpm * 2)
keypress("z", x, bpm * 2)
keypress("y", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("z", x, bpm * 2)
keypress("d", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(3, bpm * 2)
keypress("y", x, bpm * 2)
keypress("r", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("d", x, bpm * 2)
keypress("a", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
keypress("f", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("x", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(3, bpm * 2)
keypress("s", x, bpm * 2)
keypress("l", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("v", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("P", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("h", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("J", x, bpm * 2)
keypress("P", x, bpm * 2)
keypress("o", x, bpm * 2)
keypress("B", x, bpm * 2)
keypress("J", x, bpm * 2)
keypress("h", x, bpm * 2)
rest(3, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("j", x, bpm * 2)
keypress("g", x, bpm * 2)
keypress("s", x, bpm * 2)
rest(1, bpm * 2)
keypress("j", x, bpm * 2)
keypress("b", x, bpm * 2)
rest(1, bpm * 2)
keypress("J", x, bpm * 2)
keypress("B", x, bpm * 2)
rest(1, bpm * 2)
keypress("l", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("z", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("x", x, bpm * 2)
rest(1, bpm * 2)
keypress("u", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("w", x, bpm * 2)
keypress("f", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("o", x, bpm * 2)
rest(1, bpm * 2)
keypress("l", x, bpm * 2)
rest(1, bpm * 2)
keypress("z", x, bpm * 2)
rest(1, bpm * 2)
keypress("x", x, bpm * 2)
rest(1.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("b", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("c", x, bpm * 2)
rest(0.5, bpm * 2)
keypress("l", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("l", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("f", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("q", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("8", x, bpm * 2)
rest(3, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("f", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
rest(3, bpm * 2)
keypress("i", x, bpm * 2)
keypress("t", x, bpm * 2)
keypress("e", x, bpm * 2)
keypress("q", x, bpm * 2)
keypress("8", x, bpm * 2)
keypress("g", x, bpm * 2)
keypress("s", x, bpm * 2)
keypress("p", x, bpm * 2)
keypress("i", x, bpm * 2)
keypress("t", x, bpm * 2)


finishedSong()
