
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(2.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(2.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("o", x, bpm)
rest(4, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("W", x, bpm)
rest(2.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(2.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("o", x, bpm)
rest(4, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)


finishedSong()
