
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(3, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(3, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.13124999999999432, bpm)
keypress("G", x, bpm)
rest(0.13333333333332575, bpm)
keypress("J", x, bpm)
rest(1.73541666666668, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)
rest(3, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.13124999999999432, bpm)
keypress("G", x, bpm)
rest(0.13333333333332575, bpm)
keypress("J", x, bpm)
rest(1.73541666666668, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
rest(3, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("S", x, bpm)


finishedSong()
