

keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.154166666666665, bpm)
keypress("3", x, bpm)
rest(0.09583333333333499, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.154166666666665, bpm)
keypress("2", x, bpm)
rest(0.09583333333333499, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.154166666666665, bpm)
keypress("1", x, bpm)
rest(0.09583333333333499, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.158333333333335, bpm)
keypress("3", x, bpm)
rest(0.09166666666666501, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.15416666666666856, bpm)
keypress("0", x, bpm)
rest(0.16041666666666288, bpm)
keypress("e", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.15416666666666856, bpm)
keypress("9", x, bpm)
rest(0.16041666666666288, bpm)
keypress("w", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.15416666666666856, bpm)
keypress("8", x, bpm)
rest(0.16041666666666288, bpm)
keypress("q", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.15416666666666856, bpm)
keypress("0", x, bpm)
rest(0.16041666666666288, bpm)
keypress("e", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.15416666666666856, bpm)
keypress("0", x, bpm)
rest(0.16041666666666288, bpm)
keypress("e", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.15416666666666856, bpm)
keypress("9", x, bpm)
rest(0.16041666666666288, bpm)
keypress("w", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.15416666666666856, bpm)
keypress("8", x, bpm)
rest(0.16041666666666288, bpm)
keypress("q", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.15416666666666856, bpm)
keypress("0", x, bpm)
rest(0.16041666666666288, bpm)
keypress("e", x, bpm)
rest(0.18541666666666856, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08333333333334281, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08333333333334281, bpm)
keypress("h", x, bpm)
rest(0.1666666666666572, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)


finishedSong()
