

keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(0.16249999999999432, bpm)
keypress("z", x, bpm)
rest(0.3375000000000057, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.16249999999999432, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.08750000000000568, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(4.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(2, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.16249999999999432, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
rest(0.3375000000000057, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.16249999999999432, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.08750000000000568, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)


finishedSong()
