

keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
keypress("8", x, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("c", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("c", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
rest(0.125, bpm)
keypress("c", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("g", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("x", x, bpm)
rest(0.12083333333333712, bpm)
keypress("c", x, bpm)
rest(0.12083333333333712, bpm)
keypress("v", x, bpm)


finishedSong()
