

keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("5", x, bpm)
rest(0.125, bpm)
keypress("$", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("T", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666643, bpm)
keypress("T", x, bpm)
rest(0.1666666666666714, bpm)
keypress("r", x, bpm)
rest(0.1666666666666643, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
rest(0.1666666666666714, bpm)
keypress("w", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
rest(0.1666666666666714, bpm)
keypress("r", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
keypress("9", x, bpm)
rest(0.1666666666666643, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.1666666666666643, bpm)
keypress("e", x, bpm)
rest(0.1666666666666714, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666643, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.1666666666666643, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666643, bpm)
keypress("T", x, bpm)
rest(0.1666666666666714, bpm)
keypress("r", x, bpm)
rest(0.1666666666666643, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
rest(0.1666666666666714, bpm)
keypress("r", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
rest(0.1666666666666714, bpm)
keypress("w", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
rest(0.1666666666666714, bpm)
keypress("r", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("w", x, bpm)
keypress("9", x, bpm)
rest(0.1666666666666643, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.1666666666666643, bpm)
keypress("e", x, bpm)
rest(0.1666666666666714, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666643, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.1666666666666643, bpm)
keypress("Q", x, bpm)
rest(0.1666666666666714, bpm)
keypress("e", x, bpm)
rest(0.1666666666666643, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.08749999999999858, bpm)
keypress("D", x, bpm)
rest(0.08749999999999858, bpm)
keypress("G", x, bpm)
rest(0.08750000000000568, bpm)
keypress("k", x, bpm)
rest(0.23749999999999716, bpm)
keypress("y", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("Y", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("k", x, bpm)
rest(0.0625, bpm)
keypress("i", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("f", x, bpm)
rest(0.0625, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("Y", x, bpm)
rest(0.0625, bpm)
keypress("i", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("k", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("h", x, bpm)
rest(0.0625, bpm)
keypress("g", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("x", x, bpm)
rest(0.0625, bpm)
keypress("Y", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("k", x, bpm)
rest(0.0625, bpm)
keypress("y", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0625, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("k", x, bpm)
rest(0.0625, bpm)
keypress("i", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("f", x, bpm)
rest(0.0625, bpm)
keypress("g", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("x", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("Z", x, bpm)
rest(0.0625, bpm)
keypress("i", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("f", x, bpm)
rest(0.0625, bpm)
keypress("g", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("x", x, bpm)
rest(0.0625, bpm)
keypress("I", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("k", x, bpm)
rest(0.0625, bpm)
keypress("Z", x, bpm)
rest(0.0625, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("h", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("Z", x, bpm)
rest(0.0625, bpm)
keypress("v", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0833333333333286, bpm)
keypress("D", x, bpm)
rest(0.08333333333334281, bpm)
keypress("G", x, bpm)
rest(0.0833333333333286, bpm)
keypress("k", x, bpm)
rest(0.0833333333333286, bpm)
keypress("Z", x, bpm)
rest(0.08333333333334281, bpm)
keypress("C", x, bpm)
rest(0.0833333333333286, bpm)
keypress("p", x, bpm)
rest(0.0625, bpm)
keypress("s", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("h", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("Z", x, bpm)
rest(0.0625, bpm)
keypress("v", x, bpm)
rest(0.0625, bpm)
keypress("a", x, bpm)
rest(0.0833333333333286, bpm)
keypress("D", x, bpm)
rest(0.08333333333334281, bpm)
keypress("G", x, bpm)
rest(0.0833333333333286, bpm)
keypress("k", x, bpm)
rest(0.0833333333333286, bpm)
keypress("Z", x, bpm)
rest(0.08333333333334281, bpm)
keypress("C", x, bpm)
rest(0.0833333333333286, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("z", x, bpm)
rest(0.0625, bpm)
keypress("C", x, bpm)
rest(0.0625, bpm)
keypress("b", x, bpm)
rest(0.0625, bpm)
keypress("m", x, bpm)
rest(0.0625, bpm)
keypress("D", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("z", x, bpm)
rest(0.0625, bpm)
keypress("Z", x, bpm)
rest(0.0625, bpm)
keypress("b", x, bpm)
rest(0.0625, bpm)
keypress("m", x, bpm)
rest(0.0625, bpm)
keypress("z", x, bpm)
rest(0.0625, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("l", x, bpm)
rest(0.0625, bpm)
keypress("z", x, bpm)
rest(0.0625, bpm)
keypress("C", x, bpm)
rest(0.0625, bpm)
keypress("b", x, bpm)
rest(0.0625, bpm)
keypress("m", x, bpm)
rest(0.0625, bpm)
keypress("d", x, bpm)
rest(0.0625, bpm)
keypress("G", x, bpm)
rest(0.0625, bpm)
keypress("j", x, bpm)
rest(0.0625, bpm)
keypress("k", x, bpm)
rest(0.0625, bpm)
keypress("Z", x, bpm)
rest(0.0625, bpm)
keypress("C", x, bpm)
rest(0.0625, bpm)
keypress("b", x, bpm)
rest(0.0625, bpm)
keypress("n", x, bpm)
rest(0.0625, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("x", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("v", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("v", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("C", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("m", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("x", x, bpm)
keypress("t", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("v", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("n", x, bpm)
keypress("v", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("C", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("Z", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("x", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
keypress("m", x, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("B", x, bpm)
keypress("x", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("B", x, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("V", x, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("b", x, bpm)
keypress("L", x, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("m", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("m", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("Z", x, bpm)
rest(0.125, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
keypress("x", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)


finishedSong()
