
keypress("3", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("c", x, bpm)
rest(0.875, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.125, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.085, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.09, bpm)
keypress("u", x, bpm)
rest(0.225, bpm)
keypress("p", x, bpm)
rest(0.4, bpm)
keypress("p", x, bpm)
rest(0.4, bpm)
keypress("p", x, bpm)
rest(0.2, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.4, bpm)
keypress("s", x, bpm)
rest(0.4, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.085, bpm)
keypress("q", x, bpm)
rest(0.09, bpm)
keypress("e", x, bpm)
rest(0.09, bpm)
keypress("t", x, bpm)
rest(0.135, bpm)
keypress("p", x, bpm)
rest(0.2, bpm)
keypress("p", x, bpm)
rest(1.4, bpm)
keypress("p", x, bpm)
rest(0.4, bpm)
keypress("p", x, bpm)
rest(0.2, bpm)
keypress("p", x, bpm)
rest(0.6, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.085, bpm)
keypress("r", x, bpm)
rest(0.09, bpm)
keypress("y", x, bpm)
rest(0.225, bpm)
keypress("o", x, bpm)
rest(0.4, bpm)
keypress("o", x, bpm)
rest(0.4, bpm)
keypress("o", x, bpm)
rest(0.4, bpm)
keypress("p", x, bpm)
rest(0.2, bpm)
keypress("o", x, bpm)
rest(0.2, bpm)
keypress("o", x, bpm)
rest(0.8, bpm)
keypress("i", x, bpm)
rest(0.4, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.085, bpm)
keypress("0", x, bpm)
rest(0.09, bpm)
keypress("w", x, bpm)
rest(0.09, bpm)
keypress("r", x, bpm)
rest(0.135, bpm)
keypress("u", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(1.4, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.6, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.085, bpm)
keypress("w", x, bpm)
rest(0.09, bpm)
keypress("e", x, bpm)
rest(0.09, bpm)
keypress("t", x, bpm)
rest(0.135, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
rest(0.085, bpm)
keypress("e", x, bpm)
rest(0.09, bpm)
keypress("r", x, bpm)
rest(0.225, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("y", x, bpm)
rest(0.2, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
rest(0.6, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("y", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.085, bpm)
keypress("e", x, bpm)
rest(0.09, bpm)
keypress("r", x, bpm)
rest(2.025, bpm)
keypress("u", x, bpm)
rest(0.2, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("u", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
rest(0.2, bpm)
keypress("p", x, bpm)
rest(0.4, bpm)
keypress("a", x, bpm)
rest(0.6, bpm)
keypress("O", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
rest(0.4, bpm)
keypress("O", x, bpm)
rest(0.4, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
rest(0.156, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
rest(0.469, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.469, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
rest(0.156, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("y", x, bpm)
rest(0.313, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("y", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.469, bpm)
keypress("y", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.469, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
rest(0.625, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.469, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.469, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.469, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.469, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("5", x, bpm)
rest(0.625, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("1", x, bpm)
rest(0.625, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.469, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.469, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.469, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.469, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.469, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("1", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("4", x, bpm)
rest(0.469, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("7", x, bpm)
rest(0.469, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.313, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.156, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("s", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.156, bpm)
keypress("s", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.313, bpm)
keypress("g", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.313, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("g", x, bpm)
rest(0.156, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("s", x, bpm)
rest(0.156, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
rest(0.156, bpm)
keypress("s", x, bpm)
rest(0.156, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("a", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("s", x, bpm)
rest(0.156, bpm)
keypress("a", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
rest(0.156, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("s", x, bpm)
rest(0.156, bpm)
keypress("a", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("y", x, bpm)
rest(0.156, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.469, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.469, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.156, bpm)
keypress("j", x, bpm)
rest(0.469, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1.25, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.156, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("2", x, bpm)
rest(0.625, bpm)
keypress("2", x, bpm)
rest(0.625, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.156, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.156, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.156, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("1", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(0.313, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("4", x, bpm)
rest(0.469, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("7", x, bpm)
rest(0.469, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.156, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.469, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("2", x, bpm)
rest(0.625, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.156, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("1", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("1", x, bpm)
rest(0.625, bpm)
keypress("1", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("4", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("4", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.156, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.313, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.469, bpm)
keypress("f", x, bpm)
rest(0.156, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("f", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.313, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.156, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.156, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.313, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
rest(0.156, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.313, bpm)
keypress("O", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.625, bpm)
keypress("7", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)

finishedSong()
