keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("@(Ewy", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@E", x, bpm)
rest(0.5, bpm)
keypress("Eqy", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^y", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(1, bpm)
keypress("9E", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5y", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("48", x, bpm)
rest(1, bpm)
keypress("8E", x, bpm)
rest(0.5, bpm)
keypress("48", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4y", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@y", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^E", x, bpm)
rest(0.5, bpm)
keypress("^E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^y", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("9w", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5y", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("48", x, bpm)
rest(1, bpm)
keypress("8E", x, bpm)
rest(0.5, bpm)
keypress("48E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4y", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(1, bpm)
keypress("(E", x, bpm)
rest(0.5, bpm)
keypress("@(w", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@y", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^y", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(1, bpm)
keypress("9E", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5y", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("48", x, bpm)
rest(0.5, bpm)
keypress("qE", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("48", x, bpm)
rest(0.5, bpm)
keypress("Eqy", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("E4qy", x, bpm)
rest(1, bpm)
keypress("@(Ewy", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("Ewy", x, bpm)
rest(0.5, bpm)
keypress("(Ewi", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Eqy", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Eqy", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^Eqy", x, bpm)
rest(1, bpm)
keypress("E59wy", x, bpm)
rest(1, bpm)
keypress("E9wy", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(0.5, bpm)
keypress("Ewy", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E5wy", x, bpm)
rest(1, bpm)
keypress("E48qt", x, bpm)
rest(1, bpm)
keypress("E8qt", x, bpm)
rest(0.5, bpm)
keypress("48", x, bpm)
rest(0.5, bpm)
keypress("qet", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("4qet", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("os", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("@(d", x, bpm)
rest(0.5, bpm)
keypress("os", x, bpm)
rest(0.5, bpm)
keypress("(P", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("is", x, bpm)
rest(0.5, bpm)
keypress("^is", x, bpm)
rest(0.5, bpm)
keypress("Eqid", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("EP", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.5, bpm)
keypress("Pis", x, bpm)
rest(0.5, bpm)
keypress("Pqis", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("qips", x, bpm)
rest(1, bpm)
keypress("@(", x, bpm)
rest(1, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EY", x, bpm)
rest(0.5, bpm)
keypress("os", x, bpm)
rest(0.5, bpm)
keypress("@(P", x, bpm)
rest(0.25, bpm)
keypress("od", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("is", x, bpm)
rest(0.5, bpm)
keypress("^is", x, bpm)
rest(0.5, bpm)
keypress("qE", x, bpm)
rest(0.5, bpm)
keypress("is", x, bpm)
rest(0.5, bpm)
keypress("EP", x, bpm)
rest(0.25, bpm)
keypress("od", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(0.5, bpm)
keypress("P48qis", x, bpm)
rest(1, bpm)
keypress("Pis", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("48qips", x, bpm)
rest(1, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("EPqid", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("4qi", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4qp", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("iP", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Eqis", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("48qip", x, bpm)
rest(1, bpm)
keypress("qip", x, bpm)
rest(0.5, bpm)
keypress("4qo", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("(t", x, bpm)
rest(0.5, bpm)
keypress("@(y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("(E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^t", x, bpm)
rest(0.5, bpm)
keypress("^y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("59t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9t", x, bpm)
rest(0.5, bpm)
keypress("59y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("5E", x, bpm)
rest(0.5, bpm)
keypress("48qt", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("48qy", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("qE", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@^(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@(y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^(E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^t", x, bpm)
rest(0.5, bpm)
keypress("^y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("59t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9t", x, bpm)
rest(0.5, bpm)
keypress("59y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("9E", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("5E", x, bpm)
rest(0.5, bpm)
keypress("48qt", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("48qy", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("qE", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("4E", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("(E", x, bpm)
rest(0.25, bpm)
keypress("wy", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^qt", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("^qt", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("qt", x, bpm)
rest(0.5, bpm)
keypress("^E", x, bpm)
rest(0.25, bpm)
keypress("wy", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("9wt", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(0.5, bpm)
keypress("wt", x, bpm)
rest(0.5, bpm)
keypress("9E", x, bpm)
rest(0.25, bpm)
keypress("wy", x, bpm)
rest(0.75, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
rest(0.5, bpm)
keypress("eY", x, bpm)
rest(0.5, bpm)
keypress("ey", x, bpm)
rest(0.5, bpm)
keypress("eY", x, bpm)
rest(1, bpm)
keypress("ey", x, bpm)
rest(0.5, bpm)
keypress("eY", x, bpm)
rest(0.5, bpm)
keypress("@^(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@^(", x, bpm)
rest(0.5, bpm)
keypress("os", x, bpm)
rest(0.5, bpm)
keypress("(P", x, bpm)
rest(0.25, bpm)
keypress("od", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Pig", x, bpm)
rest(0.5, bpm)
keypress("i^PD", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Pid", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.5, bpm)
keypress("Pis", x, bpm)
rest(0.5, bpm)
keypress("Pqis", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.5, bpm)
keypress("48q", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("qips", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(od", x, bpm)
rest(1, bpm)
keypress("(od", x, bpm)
rest(0.5, bpm)
keypress("EY", x, bpm)
rest(0.5, bpm)
keypress("@(od", x, bpm)
rest(0.5, bpm)
keypress("os", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^id", x, bpm)
rest(0.5, bpm)
keypress("id", x, bpm)
rest(0.5, bpm)
keypress("^id", x, bpm)
rest(0.5, bpm)
keypress("qE", x, bpm)
rest(0.5, bpm)
keypress("id", x, bpm)
rest(0.5, bpm)
keypress("Eos", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("59w", x, bpm)
rest(0.5, bpm)
keypress("Pyod", x, bpm)
rest(0.5, bpm)
keypress("Pwyod", x, bpm)
rest(0.5, bpm)
keypress("59", x, bpm)
rest(0.5, bpm)
keypress("P48qis", x, bpm)
rest(1, bpm)
keypress("Pis", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("48qips", x, bpm)
rest(1, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Pqid", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("4qi", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4qp", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("iP", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Eqis", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("48qip", x, bpm)
rest(1, bpm)
keypress("qip", x, bpm)
rest(0.5, bpm)
keypress("4qo", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Pqid", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("4qi", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4qp", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("iP", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("qis", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("4qip", x, bpm)
rest(1, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
rest(1, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("oYD", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("(d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("yiD", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("ED", x, bpm)
rest(0.5, bpm)
keypress("^d", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("Yd", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("(d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("yD", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("ED", x, bpm)
rest(0.5, bpm)
keypress("^d", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("qip", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("qip", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("Yd", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("(d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("yiD", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("iED", x, bpm)
rest(0.5, bpm)
keypress("^d", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("qip", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("tip", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("Yd", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("(d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("yiD", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("ED", x, bpm)
rest(0.5, bpm)
keypress("^d", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("qip", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("qip", x, bpm)
rest(1, bpm)
keypress("@(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("Yd", x, bpm)
rest(0.5, bpm)
keypress("oED", x, bpm)
rest(0.5, bpm)
keypress("(d", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("yoD", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("ED", x, bpm)
rest(0.5, bpm)
keypress("^d", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4qips", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("qiP", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Pqid", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("4qi", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4qp", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("iP", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("Eqis", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("48qip", x, bpm)
rest(1, bpm)
keypress("qip", x, bpm)
rest(0.5, bpm)
keypress("4qo", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("EPqid", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("4qi", x, bpm)
rest(0.125, bpm)
keypress("P", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4qp", x, bpm)
rest(0.5, bpm)
keypress("ips", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("iP", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("@(os", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("(os", x, bpm)
rest(0.5, bpm)
keypress("EYP", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@(", x, bpm)
rest(0.5, bpm)
keypress("o@(PD", x, bpm)
rest(0.5, bpm)
keypress("4q", x, bpm)
rest(0.5, bpm)
keypress("P5wyod", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("yo", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("oPD", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("^Pid", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("qis", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("48qip", x, bpm)
rest(1, bpm)
keypress("qip", x, bpm)
rest(0.5, bpm)
keypress("4qo", x, bpm)
rest(0.5, bpm)
keypress("ip", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)

finishedSong()
