

keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("9ryk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("$Qej", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("9yQG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("50wf", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("9yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("9yd", x, bpm)
rest(0.5, bpm)
keypress("0rf", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("70f", x, bpm)
rest(0.5, bpm)
keypress("5QG", x, bpm)
rest(0.5, bpm)
keypress("7QG", x, bpm)
rest(0.5, bpm)
keypress("29d", x, bpm)
rest(0.5, bpm)
keypress("70f", x, bpm)
rest(0.5, bpm)
keypress("2QG", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*", x, bpm)
rest(0.5, bpm)
keypress("60f", x, bpm)
rest(0.5, bpm)
keypress("6QG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("5QG", x, bpm)
rest(0.5, bpm)
keypress("7QG", x, bpm)
rest(0.5, bpm)
keypress("29d", x, bpm)
rest(0.5, bpm)
keypress("70f", x, bpm)
rest(0.5, bpm)
keypress("2QG", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*", x, bpm)
rest(0.5, bpm)
keypress("60f", x, bpm)
rest(0.5, bpm)
keypress("6QG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("$Q7a", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("rk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("rk", x, bpm)
rest(0.25, bpm)
keypress("ej", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7erj", x, bpm)
rest(0.5, bpm)
keypress("9eyj", x, bpm)
rest(0.5, bpm)
keypress("$Qej", x, bpm)
rest(0.25, bpm)
keypress("ej", x, bpm)
rest(0.25, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("79rd", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("QI0f", x, bpm)
rest(0.5, bpm)
keypress("$Q0f", x, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.25, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("*T0f", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("$Q7a", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("rk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("rk", x, bpm)
rest(0.5, bpm)
keypress("$Qrk", x, bpm)
rest(0.25, bpm)
keypress("ej", x, bpm)
rest(0.25, bpm)
keypress("7r", x, bpm)
rest(0.25, bpm)
keypress("ej", x, bpm)
rest(0.25, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q9ypz", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("79rd", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("QI0f", x, bpm)
rest(0.5, bpm)
keypress("$Q0f", x, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.25, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("*T0f", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("$7a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("6epj", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("67rak", x, bpm)
rest(0.5, bpm)
keypress("26epj", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("350woh", x, bpm)
rest(0.5, bpm)
keypress("$QIG", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7a", x, bpm)
rest(0.5, bpm)
keypress("7$QIG", x, bpm)
rest(0.5, bpm)
keypress("30uf", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6$QIG", x, bpm)
rest(0.5, bpm)
keypress("230uf", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("2390yd", x, bpm)
rest(0.5, bpm)
keypress("$QIG", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(1, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("6epj", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("67erak", x, bpm)
rest(0.5, bpm)
keypress("269epj", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(1, bpm)
keypress("350wuoh", x, bpm)
rest(0.5, bpm)
keypress("$QIG", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("$Q6epj", x, bpm)
rest(0.5, bpm)
keypress("57wrak", x, bpm)
rest(0.5, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("7rQIGC", x, bpm)
rest(0.5, bpm)
keypress("0ufx", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("6eQIGC", x, bpm)
rest(0.5, bpm)
keypress("290ufx", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(1, bpm)
keypress("390yudz", x, bpm)
rest(0.5, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("29ryk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("29ej", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.5, bpm)
keypress("!*QTG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("390ud", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)

keypress("$Q7a", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9eyj", x, bpm)
rest(0.25, bpm)
keypress("rk", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5wrk", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("7erj", x, bpm)
rest(0.25, bpm)
keypress("ej", x, bpm)
rest(0.75, bpm)
keypress("$Qej", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9eyj", x, bpm)
rest(0.25, bpm)
keypress("yz", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5wyz", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("79rd", x, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.75, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("70rf", x, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.75, bpm)

keypress("$Q0f", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("QI0f", x, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("50wf", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("*T0f", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("7a", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("rk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("rk", x, bpm)
rest(0.25, bpm)
keypress("ej", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7erj", x, bpm)
rest(0.5, bpm)
keypress("9eyj", x, bpm)
rest(0.25, bpm)
keypress("yz", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5wyz", x, bpm)
rest(1, bpm)
keypress("79rd", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("9y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("0rf", x, bpm)
rest(0.5, bpm)
keypress("QI0f", x, bpm)
rest(0.5, bpm)
keypress("$Q0f", x, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.25, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("*T0f", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("$7a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("6epj", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("67rak", x, bpm)
rest(0.5, bpm)
keypress("26epj", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("350woh", x, bpm)
rest(0.5, bpm)
keypress("$QIG", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("7ra", x, bpm)
rest(0.5, bpm)
keypress("7$QIG", x, bpm)
rest(0.5, bpm)
keypress("30uf", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6$QIG", x, bpm)
rest(0.5, bpm)
keypress("230uf", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("2390yd", x, bpm)
rest(0.5, bpm)
keypress("$QIG", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(1, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("6epj", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("67erak", x, bpm)
rest(0.5, bpm)
keypress("269epj", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(1, bpm)
keypress("350wuoh", x, bpm)
rest(0.5, bpm)
keypress("$QIG", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("$Q6epj", x, bpm)
rest(0.5, bpm)
keypress("57wrak", x, bpm)
rest(0.5, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("7rQIGC", x, bpm)
rest(0.5, bpm)
keypress("0ufx", x, bpm)
rest(0.5, bpm)
keypress("29", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("6eQIGC", x, bpm)
rest(0.5, bpm)
keypress("290ufx", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(1, bpm)
keypress("390yudz", x, bpm)
rest(0.5, bpm)
keypress("7rak", x, bpm)
rest(0.5, bpm)
keypress("$Q", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("29ryk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("29ej", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.5, bpm)
keypress("!*QTG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("390ud", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("$Q7a", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("5w", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("29ryk", x, bpm)
rest(0.5, bpm)
keypress("7rk", x, bpm)
rest(0.5, bpm)
keypress("29ej", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.5, bpm)
keypress("!*QTG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("390ud", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("$QG", x, bpm)
rest(0.5, bpm)
keypress("7r", x, bpm)
rest(0.5, bpm)
keypress("29y", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("5wQG", x, bpm)
rest(0.5, bpm)
keypress("7rQG", x, bpm)
rest(0.5, bpm)
keypress("29yd", x, bpm)
rest(0.5, bpm)
keypress("70rf", x, bpm)
rest(0.5, bpm)
keypress("29QG", x, bpm)
rest(0.5, bpm)
keypress("6e", x, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("!*T", x, bpm)
rest(0.5, bpm)
keypress("60ef", x, bpm)
rest(0.5, bpm)
keypress("6eQG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
keypress("30u", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.5, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("0f", x, bpm)
rest(0.5, bpm)
keypress("QG", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9d", x, bpm)
rest(0.5, bpm)
keypress("7a", x, bpm)
rest(0.25, bpm)

finishedSong()
