

keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.19583333333333997, bpm)
keypress("k", x, bpm)
rest(1.80416666666666, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.19583333333333997, bpm)
keypress("a", x, bpm)
rest(0.19999999999998863, bpm)
keypress("f", x, bpm)
rest(0.6041666666666714, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.1979166666666714, bpm)
keypress("G", x, bpm)
rest(0.8020833333333286, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.19583333333332575, bpm)
keypress("k", x, bpm)
rest(1.8041666666666742, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.1979166666666572, bpm)
keypress("a", x, bpm)
rest(0.19791666666668561, bpm)
keypress("f", x, bpm)
rest(0.6041666666666572, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(0.1979166666666572, bpm)
keypress("H", x, bpm)
rest(0.8020833333333428, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("(", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.6666666666666572, bpm)
keypress("r", x, bpm)
rest(0.3333333333333428, bpm)
keypress("(", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("(", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.6666666666666572, bpm)
keypress("r", x, bpm)
rest(0.3333333333333428, bpm)
keypress("*", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("*", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666856, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
rest(0.3333333333333428, bpm)
keypress("*", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("7", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.6666666666666572, bpm)
keypress("r", x, bpm)
rest(0.3333333333333428, bpm)
keypress("7", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("7", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("$", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
rest(0.3333333333333428, bpm)
keypress("@", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
rest(0.3333333333333428, bpm)
keypress("^", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("(", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
rest(0.6666666666666572, bpm)
keypress("r", x, bpm)
rest(0.3333333333333428, bpm)
keypress("(", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("W", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.6666666666666572, bpm)
keypress("r", x, bpm)
rest(0.3333333333333428, bpm)
keypress("*", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("*", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666856, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
rest(0.3333333333333428, bpm)
keypress("*", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("7", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("7", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
rest(0.3333333333333428, bpm)
keypress("7", x, bpm)
rest(0.3333333333333428, bpm)
keypress("Y", x, bpm)
rest(0.6666666666666572, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
rest(0.3333333333333428, bpm)
keypress("@", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.6666666666666572, bpm)
keypress("T", x, bpm)
rest(0.3333333333333428, bpm)
keypress("^", x, bpm)
rest(0.3333333333333428, bpm)
keypress("r", x, bpm)
rest(0.6666666666666572, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.03541666666666288, bpm)
keypress("O", x, bpm)
rest(0.039583333333325754, bpm)
keypress("a", x, bpm)


finishedSong()
