

keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08124999999999716, bpm)
keypress("$", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08541666666666003, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.08124999999999716, bpm)
keypress("$", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08541666666666003, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08124999999999716, bpm)
keypress("%", x, bpm)
rest(0.08333333333334281, bpm)
keypress("7", x, bpm)
rest(0.08541666666666003, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08124999999999716, bpm)
keypress("$", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08541666666666003, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08124999999999716, bpm)
keypress("%", x, bpm)
rest(0.08333333333334281, bpm)
keypress("7", x, bpm)
rest(0.08541666666666003, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08124999999999716, bpm)
keypress("$", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08541666666666003, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.08124999999999716, bpm)
keypress("$", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08541666666666003, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08124999999999716, bpm)
keypress("%", x, bpm)
rest(0.08333333333334281, bpm)
keypress("7", x, bpm)
rest(0.08541666666666003, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08124999999999716, bpm)
keypress("*", x, bpm)
rest(0.08333333333334281, bpm)
keypress("0", x, bpm)
rest(0.08541666666666003, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08124999999999716, bpm)
keypress("$", x, bpm)
rest(0.08333333333334281, bpm)
keypress("6", x, bpm)
rest(0.08541666666666003, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08124999999999716, bpm)
keypress("%", x, bpm)
rest(0.08333333333334281, bpm)
keypress("7", x, bpm)
rest(0.08541666666666003, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.05000000000001137, bpm)
keypress("f", x, bpm)
rest(0.03333333333330302, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.014583333333348492, bpm)
keypress("j", x, bpm)
rest(0.2354166666666515, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.05000000000001137, bpm)
keypress("f", x, bpm)
rest(0.03333333333330302, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.014583333333348492, bpm)
keypress("j", x, bpm)
rest(0.2354166666666515, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.05000000000001137, bpm)
keypress("f", x, bpm)
rest(0.03333333333330302, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.014583333333348492, bpm)
keypress("j", x, bpm)
rest(0.2354166666666515, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.05000000000001137, bpm)
keypress("f", x, bpm)
rest(0.03333333333330302, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.014583333333348492, bpm)
keypress("j", x, bpm)
rest(0.2354166666666515, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.12291666666664014, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.0020833333333598603, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.12291666666664014, bpm)
keypress("j", x, bpm)
rest(0.12708333333335986, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.12291666666664014, bpm)
keypress("j", x, bpm)
rest(0.12708333333335986, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("z", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.05000000000001137, bpm)
keypress("f", x, bpm)
rest(0.03333333333330302, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.014583333333348492, bpm)
keypress("j", x, bpm)
rest(0.2354166666666515, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.05000000000001137, bpm)
keypress("f", x, bpm)
rest(0.03333333333330302, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.014583333333348492, bpm)
keypress("j", x, bpm)
rest(0.2354166666666515, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
rest(0.08125000000001137, bpm)
keypress("$", x, bpm)
rest(0.08333333333331439, bpm)
keypress("6", x, bpm)
rest(0.08541666666667425, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.08125000000001137, bpm)
keypress("%", x, bpm)
rest(0.08333333333331439, bpm)
keypress("7", x, bpm)
rest(0.08541666666667425, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.08125000000001137, bpm)
keypress("*", x, bpm)
rest(0.08333333333331439, bpm)
keypress("0", x, bpm)
rest(0.08541666666667425, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)


finishedSong()
