

keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("z", x, bpm)
rest(1.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(4, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("c", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("D", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)


finishedSong()
