

keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.20624999999999716, bpm)
keypress("s", x, bpm)
rest(0.7937500000000028, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("m", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.16249999999999432, bpm)
keypress("Z", x, bpm)
rest(0.3375000000000057, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.1666666666666714, bpm)
keypress("H", x, bpm)
rest(0.1666666666666572, bpm)
keypress("j", x, bpm)
rest(0.1666666666666714, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("O", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.20625000000001137, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.7937499999999886, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(0.1666666666666572, bpm)
keypress("L", x, bpm)
rest(0.16666666666668561, bpm)
keypress("Z", x, bpm)
rest(0.1666666666666572, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.20625000000001137, bpm)
keypress("J", x, bpm)
rest(0.20833333333331439, bpm)
keypress("H", x, bpm)
rest(5.585416666666674, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(0.20625000000001137, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.7937499999999886, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(8, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.20625000000001137, bpm)
keypress("s", x, bpm)
rest(0.7937499999999886, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("m", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(0.16250000000002274, bpm)
keypress("Z", x, bpm)
rest(0.33749999999997726, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.16666666666668561, bpm)
keypress("H", x, bpm)
rest(0.16666666666662877, bpm)
keypress("j", x, bpm)
rest(0.16666666666668561, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("O", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("T", x, bpm)
rest(0.20625000000001137, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.7937499999999886, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(0.16666666666668561, bpm)
keypress("L", x, bpm)
rest(0.16666666666662877, bpm)
keypress("Z", x, bpm)
rest(0.16666666666668561, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("v", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("s", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.20625000000001137, bpm)
keypress("J", x, bpm)
rest(0.20833333333331439, bpm)
keypress("H", x, bpm)
rest(5.585416666666674, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("O", x, bpm)
rest(0.20624999999995453, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.7937500000000455, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("w", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)


finishedSong()
