keypress("qt*WH", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("qt*WH", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("E80wh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("qtWYH", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("qt*WH", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("qt*WH", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("E80wh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)

rest(0.25, bpm)
keypress("qtWYH", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(1, bpm)

rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("qt*WD", x, bpm)
rest(1, bpm)
keypress("qt*WH", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("qt*WJ", x, bpm)
rest(1, bpm)
keypress("E80wl", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("80wEJ", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("qtWY", x, bpm)
rest(1, bpm)
keypress("qt*WH", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("qt*WH", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("qt*WD", x, bpm)
rest(1, bpm)
keypress("E80wl", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("*Wqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qt*WZ", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("E80wl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wEZ", x, bpm)
rest(0.5, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("WYqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("WYqtl", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(ETwh", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("WYqtg", x, bpm)
rest(0.5, bpm)
keypress("(ETwc", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("w(ETZ", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.5, bpm)
keypress("w(ETH", x, bpm)
rest(0.5, bpm)
keypress("*Wqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qt*WZ", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("E80wl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wEZ", x, bpm)
rest(0.5, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("WYqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("WYqtl", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(ETwh", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("WYqtg", x, bpm)
rest(0.5, bpm)
keypress("(ETwc", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("w(ETZ", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.5, bpm)
keypress("w(ETH", x, bpm)
rest(0.5, bpm)
keypress("*Wqtl", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("80wtJ", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("*Wqtl", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("80wtJ", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("WYqtl", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("(EYwg", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("qtWYH", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("qt*WD", x, bpm)
rest(1, bpm)
keypress("qt*WH", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("qt*WJ", x, bpm)
rest(1, bpm)
keypress("E80wl", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("80wEJ", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("qtWY", x, bpm)
rest(1, bpm)
keypress("qt*WH", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
rest(1, bpm)
keypress("*Wqt", x, bpm)
rest(1, bpm)
keypress("qt*WH", x, bpm)
rest(1, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("qt*WD", x, bpm)
rest(1, bpm)
keypress("E80wl", x, bpm)
rest(1, bpm)
keypress("L", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
keypress("qtWYH", x, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("*Wqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qt*WZ", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("E80wl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wEZ", x, bpm)
rest(0.5, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("WYqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("WYqtl", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(ETwh", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("WYqtg", x, bpm)
rest(0.5, bpm)
keypress("(ETwc", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("w(ETZ", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.5, bpm)
keypress("w(ETH", x, bpm)
rest(0.5, bpm)
keypress("*Wqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qt*WZ", x, bpm)
rest(0.5, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("E80wl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wEZ", x, bpm)
rest(0.5, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("WYqtl", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("qtWY", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("WYqtl", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(ETwh", x, bpm)
rest(0.5, bpm)
keypress("w(ET", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*Wqth", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("*Wqt", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("80wEH", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("80wE", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWYJ", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("qtWY", x, bpm)
rest(0.5, bpm)
keypress("WYqtg", x, bpm)
rest(0.5, bpm)
keypress("(ETwc", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("w(ETZ", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("w(ET", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("w(ETJ", x, bpm)
rest(0.5, bpm)
keypress("w(ETH", x, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("80wrk", x, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("(Qek", x, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("0wryk", x, bpm)
rest(1, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("Q9etj", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Q9et", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9etQG", x, bpm)
rest(0.5, bpm)
keypress("Q9et", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("80wr", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("(Qe", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wry", x, bpm)
rest(0.5, bpm)
keypress("0wryf", x, bpm)
rest(0.5, bpm)
keypress("Q9etx", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Q9etz", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("Q9etj", x, bpm)
rest(0.5, bpm)
keypress("Q9eth", x, bpm)
rest(0.5, bpm)
keypress("80wrk", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wr", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wr", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("80wr", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("80wrz", x, bpm)
rest(0.5, bpm)
keypress("80wr", x, bpm)
rest(0.5, bpm)
keypress("(Qek", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(Qe", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(Qe", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("(Qe", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("(Qez", x, bpm)
rest(0.5, bpm)
keypress("(Qe", x, bpm)
rest(0.5, bpm)
keypress("0wryk", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("0wry", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("0wry", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("0wry", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("0wryk", x, bpm)
rest(0.5, bpm)
keypress("0wry", x, bpm)
rest(0.5, bpm)
keypress("Q9etj", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Q9et", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("9etQG", x, bpm)
rest(0.5, bpm)
keypress("Q9et", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("80wrG", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("80wr", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("(Qeh", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("(Qe", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wryj", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("0wry", x, bpm)
rest(0.5, bpm)
keypress("0wryf", x, bpm)
rest(0.5, bpm)
keypress("Q9etx", x, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Q9etz", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q9et", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("Q9etj", x, bpm)
rest(0.5, bpm)
keypress("Q9eth", x, bpm)
rest(0.5, bpm)
keypress("80wrk", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("(Q7rj", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("80wrk", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("(Q7rj", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("0wryk", x, bpm)
rest(1, bpm)
keypress("k", x, bpm)
rest(1, bpm)
keypress("Q9eyf", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("0wryh", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
rest(1, bpm)

keypress("80wrh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("80wrh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("7e(QG", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("0wryh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("80wrh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("80wrh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("7e(QG", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(1, bpm)
rest(0.25, bpm)
keypress("0wryh", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)

finishedSong()
